import React from "react";

const LastGuide = () => {
	return (
		<div className="guide">
			<div className="content">
				<table className="table">
					<tbody className="center">
						<tr className="bold">
							<td rowSpan="2">Độ phân giảibản in
							(lpi)
							</td>
							<td rowSpan="2">Độ phân giảitrục Anilox
							(lpi)
							</td>
							<td rowSpan="2">BCM - XLT Aniloxroll (khuyến
							cáo)
							</td>
							<td rowSpan="2">Độ mởcell (μm)
							</td>
							<td rowSpan="2">Độ dày thànhvách ngăn
							(μm)
							</td>
							<td rowSpan="2">Khoảng độ sâu cell(Điều kiện:
							23-33%)
							</td>
						</tr>
						<tr>
						</tr>
						<tr>
							<td>45</td>
							<td>120</td>
							<td>11-16</td>
							<td>202</td>
							<td>9</td>
							<td>50-120</td>
						</tr>
						<tr>
							<td>45</td>
							<td>140</td>
							<td>9-14</td>
							<td>172</td>
							<td>9</td>
							<td>50-100</td>
						</tr>
						<tr>
							<td>50</td>
							<td>165</td>
							<td>7-13</td>
							<td>151</td>
							<td>8</td>
							<td>30-80</td>
						</tr>
						<tr>
							<td>50</td>
							<td>180</td>
							<td>6-11</td>
							<td>133</td>
							<td>8</td>
							<td>30-70</td>
						</tr>
						<tr>
							<td>55</td>
							<td>200</td>
							<td>5.5-10.5</td>
							<td>120</td>
							<td>7</td>
							<td>20-60</td>
						</tr>
						<tr>
							<td>55</td>
							<td>220</td>
							<td>5-10</td>
							<td>108</td>
							<td>7</td>
							<td>20-60</td>
						</tr>
						<tr>
							<td>65</td>
							<td>240</td>
							<td>4.5-9.5</td>
							<td>100</td>
							<td>6</td>
							<td>20-50</td>
						</tr>
						<tr>
							<td>65</td>
							<td>260</td>
							<td>4.5-8.5</td>
							<td>92</td>
							<td>6</td>
							<td>20-50</td>
						</tr>
						<tr>
							<td>70</td>
							<td>280</td>
							<td>4.4-8.0</td>
							<td>85</td>
							<td>6</td>
							<td>15-45</td>
						</tr>
						<tr>
							<td>70</td>
							<td>300</td>
							<td>4.3-7.5</td>
							<td>79</td>
							<td>6</td>
							<td>15-40</td>
						</tr>
						<tr>
							<td>85</td>
							<td>360</td>
							<td>3.7-6.5</td>
							<td>65</td>
							<td>5</td>
							<td>10-40</td>
						</tr>
						<tr>
							<td>85</td>
							<td>400</td>
							<td>3.7-6.0</td>
							<td>58</td>
							<td>5</td>
							<td>10-35</td>
						</tr>
						<tr>
							<td>85</td>
							<td>440</td>
							<td>2.8-4.5</td>
							<td>53</td>
							<td>5</td>
							<td>10-35</td>
						</tr>
						<tr>
							<td>100</td>
							<td>500</td>
							<td>2.7-5.2</td>
							<td>47</td>
							<td>4</td>
							<td>5-30</td>
						</tr>
						<tr>
							<td>100</td>
							<td>550</td>
							<td>2.5-5.0</td>
							<td>42</td>
							<td>4</td>
							<td>5-30</td>
						</tr>
						<tr>
							<td>120</td>
							<td>600</td>
							<td>2.3-4.5</td>
							<td>38</td>
							<td>4</td>
							<td>5-25</td>
						</tr>
						<tr>
							<td>133</td>
							<td>700</td>
							<td>2.0-4.0</td>
							<td>33</td>
							<td>3</td>
							<td>5-20</td>
						</tr>
						<tr>
							<td>133</td>
							<td>800</td>
							<td>1.5-3.5</td>
							<td>29</td>
							<td>3</td>
							<td>5-15</td>
						</tr>
						<tr>
							<td>140</td>
							<td>900</td>
							<td>1.3-3.0</td>
							<td>25</td>
							<td>3</td>
							<td>5-15</td>
						</tr>
						<tr>
							<td>140</td>
							<td>1000</td>
							<td>1.1-2.2</td>
							<td>22</td>
							<td>3</td>
							<td>5-10</td>
						</tr>
						<tr>
							<td>150</td>
							<td>1200</td>
							<td>1.0-2.0</td>
							<td>19</td>
							<td>2</td>
							<td>3-10</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	);
};

export default LastGuide;